# Generated by Django 5.0.3 on 2024-04-02 10:39

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('encrypted_mobile', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
    ]
